Created section for booking a venue
MarekKluk/PD19FirstFigmaProject pull request #9
Opened 2022-11-27 17:39 UTC by MarekKluk

2022-11-28 17:50 UTC, Solnick requested changes

2022-11-28 17:50 UTC, Solnick commented on src/shared/components/StyledSlider/index.jsx
> +const celadonColor = getComputedStyle(document.documentElement).getPropertyValue('--celadon')
Wow, this is not the intended way of doing it. I guess you had troubles with using css variable in the js code. You can do it either way:
- create js variable with this colour and use it
- define new color in theme and use it through props, like this
```
export const StyledSlider = styled(Slider)((theme) => ({
  color: theme.celadonColor,
  ```
  And naming colors with color names is not good option. Imagine that your designer wants to change color from celadon to purple? What do you do? You change the value of the celedon variable, and the name is not valid rn. You should use names like `primaryColor` `secondaryColor`, `mainColor`, `backgroundBaseColor`, `textContrastPrimary` etc. You can read more about theming in the material ui docs

2022-11-28 17:50 UTC, Solnick commented on src/views/VenuesListWithFilter/FilterList/index.jsx
>            priceValue={priceValue}
Indent props

2022-11-28 17:50 UTC, Solnick commented on src/views/VenuesListWithFilter/VenuesList/Venue/index.jsx
> +            backgroundImage: `url(${venue.landingImgUrl})`
indent this line

2022-11-28 18:05 UTC, Solnick requested changes

2022-11-28 18:05 UTC, Solnick commented on src/views/VenueDetails/VenueDescription/Description/CustomListItem/index.jsx
> +}
![gif](https://media.tenor.com/ax0wvn_16NwAAAAC/sad-crying.gif)

2022-11-28 18:05 UTC, Solnick commented on src/views/VenueDetails/VenueDescription/Description/index.jsx
> +            <CustomListItem key={`${feature}-${index}`} feature={feature} />
Don't use indexes as keys, `feature` should be enough

2022-11-28 18:05 UTC, Solnick commented on src/views/VenueDetails/VenueDescription/VenueImgContainer/styles.module.css
> +    height: 352px;
Are you sure that you want fixed height size? What about mobile view?

2022-11-28 18:05 UTC, Solnick commented on src/Layout/Header/SearchBox/index.jsx
> +  const [value, setValue] = useState([null, null])
value is not the most descriptive variable name that I can imagine :D

2022-11-28 18:05 UTC, Solnick commented on src/views/VenueDetails/BookVenue/Calendar/index.jsx
> +export function Calendar ({ value, setValue }) {
You need 2 calendars? StyledDataRangePicker and StaticDateRangePicker? Can you explain what is going on here?

2022-11-28 18:05 UTC, Solnick commented on src/views/VenueDetails/BookVenue/index.jsx
> +  const [value, setValue] = useState([null, null])
value is not the most descriptive variable name that I can imagine :D

2022-11-28 18:05 UTC, Solnick commented on src/views/VenueDetails/BookVenue/index.jsx
> +const dayInMilliseconds = 24 * 60 * 60 * 1000
`const DAY_IN_MILISECONDS = …`
The thing with the const that are valuated once per file (in the compilation process) is that you should use upper case with `_` sign. That's the standard

2022-11-28 18:05 UTC, Solnick commented on src/views/VenueDetails/BookVenue/index.jsx
>    return (
This template seems to be too big, and too repeatable. Refactor it to make it more readable

2022-11-28 18:06 UTC, Solnick commented
Please remember that this should look like in the designs also for mobile users, I didn't saw single media-query in the code. Let me know if this is because you are genius and wrote all the styles to match all of the devices, or you just skipped the RWD requirement?

2022-12-05 17:46 UTC, Solnick requested changes

2022-12-05 17:46 UTC, Solnick commented on src/views/VenueDetails/BookVenue/Calendar/index.jsx
> +  let makeSpaceForCalendar = 400
it can be `const`, isn't it?

2022-12-05 17:46 UTC, Solnick commented on src/views/VenueDetails/BookVenue/Calendar/index.jsx
> +  const checkIfMobile = useMediaQuery('@media only screen and (hover: none) and (pointer: coarse)')
Why did you build such a `mediaQuery` condition? Why not screen under 600px of width or anything connected to the width?
I'm not saying that this is wrong, but I would like you to elaborate on this one.

2022-12-05 17:46 UTC, Solnick commented on src/views/VenueDetails/BookVenue/Calendar/index.jsx
> +        disablepast={true}
can be `disablepast`

2022-12-05 17:46 UTC, Solnick commented on src/views/VenueDetails/BookVenue/Calendar/styles.module.css
> +.checkboxContainer {
WUT?

2022-12-05 17:46 UTC, Solnick commented on src/views/VenueDetails/BookVenue/index.jsx
> +          apikey: 'NrQIQreA18mCUi76aT6IACgTitJMd8u4'
Move this kind of sensitive informations out of the code. Create `.env` file and then use `process.env.VARIABLE_NAME` 
https://create-react-app.dev/docs/adding-custom-environment-variables/

2022-12-05 17:46 UTC, Solnick commented on src/views/VenuesListWithFilter/index.jsx
> +          apikey: 'NrQIQreA18mCUi76aT6IACgTitJMd8u4'
Same as above

2022-12-05 17:50 UTC, Solnick requested changes

2022-12-05 17:50 UTC, Solnick commented on src/shared/components/StyledDialog/index.jsx
> +export const StyledDialog = styled(Dialog)(() => ({
```
export const StyledDialog = styled(Dialog)`
  '& .MuiPaper-root': {
    minWidth: '682px',
    maxWidth: '3000px'
  }
`
```

2022-12-05 17:50 UTC, Solnick commented on src/shared/components/StyledDialog/index.jsx
> +    minWidth: '682px',
What about mobile view?

2022-12-05 17:50 UTC, Solnick commented on src/views/VenueDetails/VenueDescription/Gallery/GalleryDialog/CarouselImgContainer/index.jsx
> +             backgroundImage: `url(${imgSrc})`
PLS DON'T USE INLINE STYLES ;_;

2022-12-06 18:14 UTC, MarekKluk commented on src/views/VenueDetails/BookVenue/Calendar/index.jsx
> +  const checkIfMobile = useMediaQuery('@media only screen and (hover: none) and (pointer: coarse)')
I just needed an information if its mobile or desktop version, no matter the width.

2022-12-21 17:02 UTC, Solnick approved these changes

2022-12-21 17:03 UTC, merged